### ISSUE TITLE
File missing: s3dis_sampled.txt

### ISSUE THREAD

**Issue by Ritchizh** [jingdao/learn_region_grow#7]
Please provide the file used in test_region_grow.py:
data/s3dis/metadata/s3dis_sampled.txt
and `room_name_file = 'data/%s_room_name.txt' % AREA` -- room_name.txt

Probably, this should be one of the files from PointNet S3DIS preprocessing routine: https://github.com/charlesq34/pointnet/tree/master/sem_seg/meta

**Comment by jingdao** [comment]
Thank you for pointing this out. The missing files have been added in the latest commit [here](https://github.com/jingdao/learn_region_grow/commit/f9a7868785bec428b95137ca8a2e7898f9bde711)

**Comment by Ritchizh** [comment]
Thank you! Now it works.
